# Explore the dataset

In [2]:
import numpy as np
import h5py
import matplotlib.pyplot as plt

In [11]:
# Load the data set

data = h5py.File('../data/SOMA/init_data/thedataset.hdf5', 'r')
print(data.keys())
print(len(data.keys()))

<KeysViewHDF5 ['forward_0', 'forward_1', 'forward_10', 'forward_100', 'forward_101', 'forward_102', 'forward_103', 'forward_104', 'forward_105', 'forward_106', 'forward_107', 'forward_108', 'forward_109', 'forward_11', 'forward_110', 'forward_111', 'forward_112', 'forward_113', 'forward_114', 'forward_115', 'forward_116', 'forward_117', 'forward_118', 'forward_119', 'forward_12', 'forward_120', 'forward_121', 'forward_122', 'forward_123', 'forward_124', 'forward_125', 'forward_126', 'forward_127', 'forward_128', 'forward_129', 'forward_13', 'forward_130', 'forward_131', 'forward_132', 'forward_133', 'forward_134', 'forward_135', 'forward_136', 'forward_137', 'forward_138', 'forward_139', 'forward_14', 'forward_140', 'forward_141', 'forward_142', 'forward_143', 'forward_144', 'forward_145', 'forward_146', 'forward_147', 'forward_148', 'forward_149', 'forward_15', 'forward_150', 'forward_151', 'forward_152', 'forward_153', 'forward_154', 'forward_155', 'forward_156', 'forward_157', 'forw

In [20]:
forward_0 = data['forward_0']['month_0']
print(forward_0.shape)
print(forward_0[0, :, :, 20, 13])
print(np.unique(forward_0))
# fig, ax = plt.subplots()
# ax.imshow(forward_0[1,:,:,0,10])


(3, 185, 309, 60, 15)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0.]
